# Generated by Django 2.2.24 on 2023-02-21 17:50

import apps.sellers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_Code', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('seller_Type', models.CharField(choices=[('Professional seller', 'Professional seller'), ('On the go seller', 'On the go seller')], max_length=20)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.sellers.models.seller_logo_path)),
                ('reg_Number', models.CharField(blank=True, max_length=120, null=True)),
                ('nature', models.CharField(choices=[('Goods', 'Goods'), ('Services', 'Services'), ('Both', 'Both')], max_length=20)),
                ('postal_Address', models.CharField(blank=True, max_length=120, null=True)),
                ('physical_Address', models.CharField(blank=True, max_length=120, null=True)),
                ('geo_Address', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('phone1', models.CharField(blank=True, max_length=120, null=True)),
                ('phone2', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('web', models.URLField(blank=True, max_length=120, null=True, verbose_name='Web Address')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('arrival_Date', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=120, null=True)),
                ('destination', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_seller', to='sellers.Seller')),
            ],
        ),
    ]
